[package]
name = "partish"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
crossterm = "0.29.0"
portable-pty = "0.9.0"
ratatui = "0.29.0"
tokio = { version = "1.48.0", features = ["macros", "sync"] }
