[package]
name = "partish"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
crossterm = "0.29.0"
derive_more = { version = "2.0.1", features = ["from"] }
portable-pty = "0.9.0"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }

[dev-dependencies]
indoc = "2.0.7"
