[package]
name = "ratatui-rctx"
version = "0.1.0"
edition.workspace = true

[dependencies]
derive-new.workspace = true
derive_more = { workspace = true, features = ["from"] }
ratatui.workspace = true
tui-textarea.workspace = true
