[package]
name = "ratatui-rseq"
version = "0.1.0"
edition.workspace = true

[dependencies]
debug-rollup.workspace = true
derive-debug.workspace = true
derive-new.workspace = true
ratatui.workspace = true
tracing.workspace = true
tui-textarea.workspace = true
